/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as TrainRouteImport } from './routes/train'
import { Route as RelationshipsRouteImport } from './routes/relationships'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ParallelRouteImport } from './routes/parallel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GeographicRouteImport } from './routes/geographic'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrudRouteImport } from './routes/crud'
import { Route as CompositionRouteImport } from './routes/composition'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsRoute = RelationshipsRouteImport.update({
  id: '/relationships',
  path: '/relationships',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ParallelRoute = ParallelRouteImport.update({
  id: '/parallel',
  path: '/parallel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GeographicRoute = GeographicRouteImport.update({
  id: '/geographic',
  path: '/geographic',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrudRoute = CrudRouteImport.update({
  id: '/crud',
  path: '/crud',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositionRoute = CompositionRouteImport.update({
  id: '/composition',
  path: '/composition',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/comparison': typeof ComparisonRoute
  '/composition': typeof CompositionRoute
  '/crud': typeof CrudRoute
  '/dashboard': typeof DashboardRoute
  '/distribution': typeof DistributionRoute
  '/forecast': typeof ForecastRoute
  '/geographic': typeof GeographicRoute
  '/login': typeof LoginRoute
  '/parallel': typeof ParallelRoute
  '/profile': typeof ProfileRoute
  '/radar': typeof RadarRoute
  '/relationships': typeof RelationshipsRoute
  '/train': typeof TrainRoute
  '/trends': typeof TrendsRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/comparison': typeof ComparisonRoute
  '/composition': typeof CompositionRoute
  '/crud': typeof CrudRoute
  '/dashboard': typeof DashboardRoute
  '/distribution': typeof DistributionRoute
  '/forecast': typeof ForecastRoute
  '/geographic': typeof GeographicRoute
  '/login': typeof LoginRoute
  '/parallel': typeof ParallelRoute
  '/profile': typeof ProfileRoute
  '/radar': typeof RadarRoute
  '/relationships': typeof RelationshipsRoute
  '/train': typeof TrainRoute
  '/trends': typeof TrendsRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/comparison': typeof ComparisonRoute
  '/composition': typeof CompositionRoute
  '/crud': typeof CrudRoute
  '/dashboard': typeof DashboardRoute
  '/distribution': typeof DistributionRoute
  '/forecast': typeof ForecastRoute
  '/geographic': typeof GeographicRoute
  '/login': typeof LoginRoute
  '/parallel': typeof ParallelRoute
  '/profile': typeof ProfileRoute
  '/radar': typeof RadarRoute
  '/relationships': typeof RelationshipsRoute
  '/train': typeof TrainRoute
  '/trends': typeof TrendsRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-setup'
    | '/comparison'
    | '/composition'
    | '/crud'
    | '/dashboard'
    | '/distribution'
    | '/forecast'
    | '/geographic'
    | '/login'
    | '/parallel'
    | '/profile'
    | '/radar'
    | '/relationships'
    | '/train'
    | '/trends'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-setup'
    | '/comparison'
    | '/composition'
    | '/crud'
    | '/dashboard'
    | '/distribution'
    | '/forecast'
    | '/geographic'
    | '/login'
    | '/parallel'
    | '/profile'
    | '/radar'
    | '/relationships'
    | '/train'
    | '/trends'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/admin-setup'
    | '/comparison'
    | '/composition'
    | '/crud'
    | '/dashboard'
    | '/distribution'
    | '/forecast'
    | '/geographic'
    | '/login'
    | '/parallel'
    | '/profile'
    | '/radar'
    | '/relationships'
    | '/train'
    | '/trends'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSetupRoute: typeof AdminSetupRoute
  ComparisonRoute: typeof ComparisonRoute
  CompositionRoute: typeof CompositionRoute
  CrudRoute: typeof CrudRoute
  DashboardRoute: typeof DashboardRoute
  DistributionRoute: typeof DistributionRoute
  ForecastRoute: typeof ForecastRoute
  GeographicRoute: typeof GeographicRoute
  LoginRoute: typeof LoginRoute
  ParallelRoute: typeof ParallelRoute
  ProfileRoute: typeof ProfileRoute
  RadarRoute: typeof RadarRoute
  RelationshipsRoute: typeof RelationshipsRoute
  TrainRoute: typeof TrainRoute
  TrendsRoute: typeof TrendsRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships': {
      id: '/relationships'
      path: '/relationships'
      fullPath: '/relationships'
      preLoaderRoute: typeof RelationshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel': {
      id: '/parallel'
      path: '/parallel'
      fullPath: '/parallel'
      preLoaderRoute: typeof ParallelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geographic': {
      id: '/geographic'
      path: '/geographic'
      fullPath: '/geographic'
      preLoaderRoute: typeof GeographicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crud': {
      id: '/crud'
      path: '/crud'
      fullPath: '/crud'
      preLoaderRoute: typeof CrudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composition': {
      id: '/composition'
      path: '/composition'
      fullPath: '/composition'
      preLoaderRoute: typeof CompositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSetupRoute: AdminSetupRoute,
  ComparisonRoute: ComparisonRoute,
  CompositionRoute: CompositionRoute,
  CrudRoute: CrudRoute,
  DashboardRoute: DashboardRoute,
  DistributionRoute: DistributionRoute,
  ForecastRoute: ForecastRoute,
  GeographicRoute: GeographicRoute,
  LoginRoute: LoginRoute,
  ParallelRoute: ParallelRoute,
  ProfileRoute: ProfileRoute,
  RadarRoute: RadarRoute,
  RelationshipsRoute: RelationshipsRoute,
  TrainRoute: TrainRoute,
  TrendsRoute: TrendsRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
